//! This module contains the auto-generated Rust structs for Knative resources.
//! These are generated using `kopium` from the Knative Serving CRDs.
//!
//! Do not edit this file directly. Instead, re-run `kopium` and update the generated files
//! in `src/resources/knative/` directory.

pub mod configuration;
pub mod route;
pub mod revision;

// Re-export the types from the sub-modules for easier access.
pub use configuration::*;
pub use route::*;
pub use revision::*;

// Common imports that are often used across these generated structs
pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::{Condition, ObjectMeta};
pub use schemars::JsonSchema;
pub use serde::{Deserialize, Serialize};
pub use std::collections::BTreeMap;
pub use kube::CustomResource; // kopium generates CustomResource derive
pub use k8s_openapi::apimachinery::pkg::util::intstr::IntOrString;