use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
use kube::CustomResource;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f routes.serving.knative.dev.yaml --derive Default --derive PartialEq --smart-derive-elision --schema=derived
// kopium version: 0.22.5

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug, Default, PartialEq, JsonSchema)]
#[kube(
    group = "serving.knative.dev",
    version = "v1",
    kind = "Route",
    plural = "routes"
)]
#[kube(namespaced)]
#[kube(status = "RouteStatus")]
#[kube(derive = "Default")]
#[kube(derive = "PartialEq")]
pub struct RouteSpec {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub traffic: Option<Vec<RouteTraffic>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq, JsonSchema)]
pub struct RouteTraffic {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "configurationName"
    )]
    pub configuration_name: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "latestRevision"
    )]
    pub latest_revision: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub percent: Option<i64>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "revisionName"
    )]
    pub revision_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq, JsonSchema)]
pub struct RouteStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address: Option<RouteStatusAddress>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub annotations: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "observedGeneration"
    )]
    pub observed_generation: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub traffic: Option<Vec<RouteStatusTraffic>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq, JsonSchema)]
pub struct RouteStatusAddress {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "CACerts")]
    pub ca_certs: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub audience: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq, JsonSchema)]
pub struct RouteStatusTraffic {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "configurationName"
    )]
    pub configuration_name: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "latestRevision"
    )]
    pub latest_revision: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub percent: Option<i64>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "revisionName"
    )]
    pub revision_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}
