apiVersion: restate.dev/v1
kind: RestateCluster
metadata:
  name: restate-test
spec:
  cluster:
    autoProvision: true
  compute:
    image: restatedev/restate:1.6.2
  config: auto-provision = false
  storage:
    storageRequestBytes: 2147483648
