apiVersion: v2
name: restate-operator-helm
description: An operator for Restate clusters
type: application
version: "3.0.0"

dependencies:
  - name: restate-operator-crds
    version: "3.0.0"
    repository: "file://../restate-operator-crds"
    condition: installCrds
