replicaCount: 1
nameOverride: "restate-operator"
version: "" # pin a specific version

image:
  repository: ghcr.io/restatedev/restate-operator
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
podAnnotations: {}

awsPodIdentityAssociationCluster: null

podSecurityContext:
  fsGroup: 2000
  fsGroupChangePolicy: "OnRootMismatch"
securityContext:
  capabilities:
   drop:
   - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000


logging:
  env_filter: info,restate=debug

env: []

affinity: {}

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 100Mi

serviceMonitor:
  enabled: false
  path: /metrics
  scheme: http
